paths:
  - ./src/Application
exclude_files:
  - "#.*Test.*#"
layers:
  ##############################
  #   Controllers
  ##############################
  - name: Controllers
    collectors:
      - type: className
        regex: ^App\\Application\\Controllers\\.*

  ##############################
  #   Services
  ##############################
  - name: Services
    collectors:
      - type: className
        regex: ^App\\Application\\Services\\.*

  ##############################
  #   Domain Repositories
  ##############################
  - name: DomainRepositories
    collectors:
      - type: className
        regex: ^App\\Domain\\Repositories\\.*

  ##############################
  #   Domain Models
  ##############################
  - name: DomainModels
    collectors:
      - type: className
        regex: ^App\\Domain\\Models\\.*

  ##############################
  #   SYMFONY
  ##############################
  - name: Symfony
    collectors:
      - type: className
        regex: ^Symfony\\.*

  ##############################
  #   DOCTRINE
  ##############################
  - name: Doctrine
    collectors:
      - type: className
        regex: ^Doctrine\\.*

ruleset:
  Controllers:
    - Services
    - DomainModels
    - Symfony
  Services:
    - DomainRepositories
    - DomainModels
    - Symfony
