# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # RequestHandlers
  App\RequestHandler\CreateUserRequestHandler: ~
  App\RequestHandler\DisableUserRequestHandler: ~
  App\RequestHandler\EnableUserRequestHandler: ~
  App\RequestHandler\RemoveUserRequestHandler: ~

  # RequestHandler interface parameter binding
  App\RequestHandler\RequestHandlerInterface $createUserRequestHandler: '@App\RequestHandler\CreateUserRequestHandler'
  App\RequestHandler\RequestHandlerInterface $disableUserRequestHandler: '@App\RequestHandler\DisableUserRequestHandler'
  App\RequestHandler\RequestHandlerInterface $enableUserRequestHandler: '@App\RequestHandler\EnableUserRequestHandler'
  App\RequestHandler\RequestHandlerInterface $removeUserRequestHandler: '@App\RequestHandler\RemoveUserRequestHandler'

  # Serializer
  App\Serializer\ObjectSerializer: ~

  # Serializer interface parameter binding
  Symfony\Component\Serializer\SerializerInterface $objectSerializer: '@App\Serializer\ObjectSerializer'
