name: Testing
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v2
        with:
          args: --no-interaction --no-progress
      - name: PHPunit
        uses: php-actions/phpunit@v2
        with:
          configuration: phpunit.xml
